---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

title: "SHWooSh Dashboard"
startUrl: http://my-ip:9000
base: http://my-ip:9000/

background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
cardBlur: sm
showStats: true
statusStyle: "dot"

target: _blank

layout:

  System:
    style: row
    columns: 5