services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - ${PORT_PORTAINER}:9443
    networks:
      - net-default
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    profiles:
      - portainer
    restart: unless-stopped

volumes:
  portainer_data: